# td-level-editor-http/src/main/resources/application.properties

# Configuration des chemins de stockage
editor.storage.base-directory=D:\\Depots\\tower_defense
editor.storage.drafts-dir=drafts
editor.storage.exportables-dir=exportables
editor.storage.towers-dir=towers
editor.storage.enemies-dir=enemies
editor.storage.levels-dir=levels

# Logging
logging.level.com.towerdefense.leveleditor.http.bootstrap=INFO