server:
  port: 8082

tdmeta:
  data:
    directory: D:/Depots/tower_defense/exportables/
  upgrades:
    file: ${TD_UPGRADES_FILE:src/main/resources/upgrades/tower-upgrades.json}

spring:
  application:
    name: td-progression-http

logging:
  level:
    com.tdmeta: DEBUG
    com.tdprogressionhttp: DEBUG