<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<artifactId>td-sequencer</artifactId>
	<description>Déroule le temps dans le tower defense</description>

	<parent>
		<groupId>com.moe</groupId>
		<artifactId>td-engine-core</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	
	<dependencies>
		<dependency>
			<groupId>com.moe</groupId>
			<artifactId>td-domain</artifactId>
			<version>0.0.1-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>com.moe</groupId>
			<artifactId>td-back-tower</artifactId>
			<version>0.0.1-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>com.moe</groupId>
			<artifactId>td-aop</artifactId>
			<version>0.0.1-SNAPSHOT</version>
		</dependency>

		<!-- Spring Core (IoC container) -->
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
			<version>6.1.3</version>
		</dependency>

		<!-- AOP Spring (nécessaire pour @Aspect + @EnableAspectJAutoProxy) -->
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-aop</artifactId>
			<version>6.1.3</version>
		</dependency>

		<!-- AspectJ (annotation @Aspect + weaver utilisé par Spring AOP) -->
		<dependency>
			<groupId>org.aspectj</groupId>
			<artifactId>aspectjweaver</artifactId>
			<version>1.9.21</version>
		</dependency>

		<!-- logback (pour LOG.info()) -->
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>1.5.6</version>
		</dependency>

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>2.0.13</version>
		</dependency>

		<!-- JUnit 5 -->
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<version>5.10.2</version>
			<scope>test</scope>
		</dependency>

		<!-- Extension Spring pour JUnit (@ExtendWith(SpringExtension.class)) -->
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-test</artifactId>
			<version>6.1.3</version>
			<scope>test</scope>
		</dependency>

	</dependencies>
</project>